### ISSUE TITLE
Organisation members

### ISSUE THREAD

**Issue by Shifterovich** [privacytools-io/privacytools-io.github.io#11]
We need members for this organisation. At the time of writing, me and @johnnagro are the only members.

Please recommend some people (even yourself), ideally those who have already contributed.

**Rules**:

* Edit files by creating PRs
* PRs like "I think we should change .............. to ................." can be merged if 2 organisation members approve the PR
* Typos must be fixed using a PR too, but there's no need for another member to approve the PR, unless it's not 100% clear
* Big changes like adding a whole new section require discussion and more approvals.

**Comment by kewde** [comment]
Hi @Shifterovich 

I'm willing to help this project, it's a shame that privacytools.io is not being maintained anymore.

**Comment by Shifterovich** [comment]
@kewde Hey. Thanks for participating. Well, it's not exactly not maintained, but the owner has not been active in a while and the project has some unresolved issues and pull requests.

What do you mean by a mirror of the website? I use GitHub pages (pointed to the master branch). https://privacytools-io.github.io/privacytools.io/ is the up-to-date version of this repository.

And I don't think there's an IRC channel, I wanted to suggest that though. I guess we can create one.

**Comment by Shifterovich** [comment]
@kewde #13

**Comment by beardog108** [comment]
I'm willing to help. I'm decently educated on security/privacy & know HTML & CSS. IMO Privacytools.io is the best privacy "starter pack", but it needs to be maintained as time passes and software evolves.

**Comment by Shifterovich** [comment]
@beardog108 sounds good. I'd invite you to the organisation, but I want to to know what someone else thinks. Could you join the IRC channel though?

**Comment by healthstr** [comment]
Wiling to help out currently in last part of my degree, studying system security and privacy.

**Comment by anthonys-io** [comment]
I can help out, finishing my degrees now and a huge privacy dude.

**Comment by georgenetu** [comment]
You can count me in, I'd love to help this project be active again.

**Comment by Shifterovich** [comment]
@healthstr @anthonys-io @georgenetu Join the IRC channel.
