### ISSUE TITLE
Rename the repository

### ISSUE THREAD

**Issue by Shifterovich** [privacytools-io/privacytools-io.github.io#22]
If we renamed the repository to `privacytools-io.github.io`, the GitHub pages link would be just `privacytools-io.github.io` insted of `privacytools-io.github.io/privacytools.io`

Thoughts?

**Comment by kewde** [comment]
Seems more than reasonable; shorter URL, easier to remember, cleaner.

**Comment by Shifterovich** [comment]
The only downside I can see is a weird repository name, but the website is what matters.

Also, @kewde connect to the IRC :P

**Comment by Shifterovich** [comment]
Renamed.

**Comment by kewde** [comment]
@Shifterovich will be on IRC in about 4 hours, currently stuck doing work.

**Comment by Shifterovich** [comment]
@kewde Awesome, no problem.
